name: Update GitHub Deployment

on: deployment_status

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment status update to GitHub
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_DEPLOYMENT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/deployments \
          -d '{
            "ref": "${{ github.sha }}",
            "environment": "production",
            "description": "Deployed via Netlify",
            "auto_merge": false,
            "required_contexts": [],
            "payload": {
              "netlify_url": "'"$DEPLOY_URL"'"
            }
          }'
